music_intervals = {
    'C minor second': 'C#',
    'C# perfect fourth': 'F#',
    'D major sixth': 'B',
    'D octave': 'D',
    'D descending major second': 'C',
    'D descending minor third': 'B',
    'D# descending diminished octave': 'E',
    'F diminished seventh': 'D',
    'F# minor third': 'A',
    'F# perfect fourth': 'B',
    'F# diminished sixth': 'C#',
    'F# augmented octave': 'G',
    'G major third': 'B',
    'G augmented fourth': 'C#',
    'G descending augmented octave': 'F#',
    'G# diminished fourth': 'C',
    'G# diminished fifth': 'D',
    'G# descending minor third': 'F',
    'A major second': 'B',
    'A perfect fourth': 'D',
    'A descending augmented fourth': 'D#',
    'A# augmented fifth': 'F#',
    'A# diminished seventh': 'G',
    'A# descending augmented fourth': 'E',
    'A# descending major seventh': 'B'
}

intervals_to_semitones = {
    'unison': '0',
    'diminished second': '0',
    'minor second': '1',
    'major second': '2',
    'augmented second': '3',
    'diminished third': '2',
    'minor third': '3',
    'major third': '4',
    'augmented third': '5',
    'diminished fourth': '4',
    'perfect fourth': '5',
    'augmented fourth': '6',
    'diminished fifth': '6',
    'perfect fifth': '7',
    'augmented fifth': '8',
    'diminished sixth': '7',
    'minor sixth': '8',
    'major sixth': '9',
    'augmented sixth': '10',
    'diminished seventh': '9',
    'minor seventh': '10',
    'major seventh': '11',
    'augmented seventh': '12',
    'diminished octave': '11',
    'octave': '12',
    'augmented octave': '13'
}


semitones_to_intervals = {
    '0': 'perfect unison',
    '1': 'minor second',
    '2': 'major second',
    '3': 'minor third',
    '4': 'major third',
    '5': 'perfect fourth',
    '6': 'augmented fourth',
    '7': 'perfect fifth',
    '8': 'minor sixth',
    '9': 'major sixth',
    '10': 'minor seventh',
    '11': 'major seventh',
    '12': 'perfect octave',
    '13': 'augmented octave'
}
